### ISSUE TITLE
Option to view full title

### ISSUE THREAD

**Issue by c-v-ya** [watch-devtube/web#103]
When we browse videos there are lots of them with truncated title. But there is no option to see the full length. I suggest to add simple `title` html attribute to `h1` with a not truncated title. So when hovering mouse over the title we could see a full text. Like on the screen below.

![image](https://user-images.githubusercontent.com/11807205/103196881-0e0fc000-48f6-11eb-8316-3dfc23a65def.png)

I believe it's just a simple fix somewhere inside `src/VideoCard.vue`. Maybe line 11? But you should know better, I'm not a Vue developer :sweat_smile:

**Comment by sizovs** [comment]
@c-v-ya Thanks for the idea, Constantine. The improvement has been released.
