### ISSUE TITLE
Can't log in using GitHub

### ISSUE THREAD

**Issue by andrey-yantsen** [watch-devtube/web#112]
After approving the github authentication I see the following message:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/629281/113474899-8d1f1200-946a-11eb-955d-86605f9c8d2f.png">

And nothing really useful in the dev console:
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/629281/113474909-9f00b500-946a-11eb-8a89-34844128d07f.png">

At the same time, Google Auth is working just fine. How can I help you debug this problem?

P.S. I'm using Safari 14.0.3 on macOS 11.2.3.

**Comment by sizovs** [comment]
Hey @andrey-yantsen 

Thanks for raising this. Could you please expand {, ...} and the log and share what's inside? A detailed message should be there.

**Comment by andrey-yantsen** [comment]
```
message: "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with thi…"
```

Yup, that explains a lot :) Thanks!
