### ISSUE TITLE
Main Search Input Styles

### ISSUE THREAD

**Issue by michaeleparkour** [watch-devtube/web#15]
I would use next styles for input:

```
header input {
    -webkit-appearance: none;
}
header input::placeholder{
    color: #fff;
}
```
At the moment grey placeholder text is hard to read on dark background and -webkit-appearance: searchfield; in Safari makes the input having white background, so typed white text is not visible.

**Comment by eduardsi** [comment]
Thanks @michaeleparkour! Done!
