### ISSUE TITLE
Optimize for mobile

### ISSUE THREAD

**Issue by djKooks** [watch-devtube/web#16]
Currently, main page looks like this in mobile browsers.

![screen shot 2018-06-26 at 15 36 42](https://user-images.githubusercontent.com/1720209/41893514-ec547f6c-7956-11e8-8ce4-e8f38020df04.png)

It is not a major issue, but seems to think about optimization for mobile devices.
Thanks.

**Comment by eduardsi** [comment]
Hey @djKooks.

You observe this on a small desktop screen, right? What would you suggest?

Thanks

**Comment by eduardsi** [comment]
I have implemented a series of layout improvements for mobile:
-  horizontal video info (saves space)
- the whole image is clickable (not only [watch] button)

Please reopen the this issue if I missed something.
