### ISSUE TITLE
Do not display Channel, Speaker, Tags etc in all Caps

### ISSUE THREAD

**Issue by kuldeepsidhu88** [watch-devtube/web#17]
Is this me or anyone else also who does not like all caps letters in Channel, Speaker, Tags etc info. Can we change it to make only the first letter caps. I think it would be more visually aesthetic. 

Apart from that, great work guys!

**Comment by eduardsi** [comment]
Done! https://github.com/watch-devtube/web/commit/eadfdd8afb454eb58f9ca936bf2fce99ec633a87

**Comment by kuldeepsidhu88** [comment]
Awesome :+1:
