### ISSUE TITLE
Make the “Tags”, “Channels”, “Speaker” headers in the left column clickable

### ISSUE THREAD

**Issue by aadamovich** [watch-devtube/web#19]
Make the “Tags”, “Channels”, “Speaker” headers in the left column clickable, so that one can see more speaker names, more channels, etc

**Comment by eduardsi** [comment]
@aadamovich I think we should speakers, channels and tags and push them together with latest.json and sitemap.xml. Then we can write a nice UI that will nicely show all speakers, channels and tags.

**Comment by aadamovich** [comment]
@eduardsi Sitemap generator now adds the following files to web:https://github.com/watch-devtube/web/blob/master/src/static/tags.json

**Comment by eduardsi** [comment]
@aadamovich mindblowing, bro. I'll work on UX.

**Comment by eduardsi** [comment]
Done!
