### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by eduardsi** [watch-devtube/web#20]
- For new additions ✅
- For videos by a given .tag
- For videos by speaker 
- For videos by channel

**Comment by aadamovich** [comment]
@eduardsi RSS is generated for latest 20 videos in https://github.com/watch-devtube/web/blob/master/src/static/rss.xml

**Comment by eduardsi** [comment]
@aadamovich connected rss.xml to the main page. Announced: https://twitter.com/WatchDevTube/status/1012633463856533504
