### ISSUE TITLE
Improve search relevance

### ISSUE THREAD

**Issue by eduardsi** [watch-devtube/web#21]
Examples of bad search results:
C++
C#
F#
Rust
Swift

**Comment by dolmen** [comment]
Perl also gets no relevant results.

**Comment by dolmen** [comment]
It looks like the content is manually populated: check the [contrib](https://github.com/watch-devtube/contrib) repo.

**Comment by eduardsi** [comment]
Relevant has been improved:
1) Algolia now understands # character (so c# and f# searches work)
2) Disabled typo tolerance, so that queries such as Kwift do not override Swift
