### ISSUE TITLE
SSL - kinda weird ...

### ISSUE THREAD

**Issue by cruizsan** [watch-devtube/web#29]
If you check your SSL (https://www.ssllabs.com/ssltest/analyze.html?d=dev.tube&s=104.31.90.114) 
as you can see, you have aliases that I would not really trust ...

![image](https://user-images.githubusercontent.com/26438518/41961188-0ffbc77c-79f2-11e8-9c5d-8a3874c45df4.png)

**Comment by aadamovich** [comment]
Interesting. Thanks for noticing! We've got that certificate from Cloudflare. Apparently it is used by several other sites.
