### ISSUE TITLE
Persistent user profile

### ISSUE THREAD

**Issue by marisveide** [watch-devtube/web#36]
I should be able to authenticate myself and have my history and “watch later” videos available from any device, so that I don’t lose that data.

Continuing serverless approach, FireBase or alike could do that.

**Comment by eduardsi** [comment]
Done! Added authentication and [watched] button. #35 is coming soon. @marisveide

**Comment by marisveide** [comment]
When I authenticate almost, but press cancel, I can cause it to crash with some unexpected error saying:
> Something went wrong!
> Please see logs and submit an issue: bit.ly/devtube-issue
![screen shot 2018-08-05 at 23 47 49](https://user-images.githubusercontent.com/17713131/43689960-af478af0-990a-11e8-8ac2-2268b53cb56e.png)

Also, my profile picture doesn't look to be a perfect circle, it's a bit stretched horizontally.

**Comment by eduardsi** [comment]
@marisveide thanks for reporting! Attempt to fix (https://github.com/watch-devtube/web/commit/d303e7a297868105f309a2b0537b0fd17877032e). Can you check the live version?

**Comment by marisveide** [comment]
Awesome, @eduardsi - that looks to be goldenly fixed now!
Don't have the unexpected error when closing the popup.
And the face is now round!

That was mega-quick! 👍
