### ISSUE TITLE
Search input styling missing for Safari

### ISSUE THREAD

**Issue by arjunkomath** [watch-devtube/web#4]
Here is how the search input looks in Chrome:

<img width="1362" alt="screen shot 2018-06-25 at 5 26 53 pm" src="https://user-images.githubusercontent.com/2555067/41852750-0e248fb6-789d-11e8-8ffe-006ab2914c1a.png">

Here is how it looks in Safari (`Version 11.1.1 (13605.2.8)`)

- Missing styles for search input
<img width="1362" alt="screen shot 2018-06-25 at 5 26 59 pm" src="https://user-images.githubusercontent.com/2555067/41852784-26e6b5ce-789d-11e8-8602-4f8c353895d4.png">

- Font color is white which is not visible
<img width="1378" alt="screen shot 2018-06-25 at 5 28 28 pm" src="https://user-images.githubusercontent.com/2555067/41852809-3dfe078a-789d-11e8-80c7-efc1400b819a.png">

**Comment by eduardsi** [comment]
Fixed.
