### ISSUE TITLE
Create night mode style

### ISSUE THREAD

**Issue by eduardsi** [watch-devtube/web#41]

**Comment by eduardsi** [comment]
@GiovanniSM20 look what I've got:

https://jenil.github.io/bulmaswatch/darkly/

I think we don't have to create a style for scratch to avoid maintenance overhead, but start with the existing one.

**Comment by GiovanniSM20** [comment]
@eduardsi sorry for the delay.

I do not know if it would be a good idea to use this, I think it's black mode is something easy to implement.

**Comment by eduardsi** [comment]
@GiovanniSM20 it will take some time to create a proper Bulma style – it has different colour combinations that needs to be overridden. More importantly, we are not UI professionals end experts in colour. We also can't just override _some_ colors, because it will make Bulma unusable. We also have to take into account maintenance costs, as Bulma, its components and style guide evolves.

I'd prefer taking existing theme created, tested and maintained by UI pro (& community) and, if we don't like it, we can create our own. Simple first!

**Comment by eduardsi** [comment]
https://twitter.com/WatchDevTube/status/1019711769739255808
