### ISSUE TITLE
Implement progressive web app (PWA) best practices

### ISSUE THREAD

**Issue by eduardsi** [watch-devtube/web#43]

**Comment by GiovanniSM20** [comment]
hey @eduardsi I've create an issue #47

**Comment by eduardsi** [comment]
Hey @GiovanniSM20. Thanks! 

We're now moving away from Algolia to save on infra expenses. Will start working on it just after we make a switch (~in a month or so).

**Comment by GiovanniSM20** [comment]
For now can I start implementing certain things ? Like #41

**Comment by eduardsi** [comment]
@GiovanniSM20 

sure, that would be highly appreciated, man!

**Comment by GiovanniSM20** [comment]
hey, @eduardsi have a channel to talk about the idea?

**Comment by eduardsi** [comment]
@GiovanniSM20 I propose keeping everything here so the communication history is visible

**Comment by GiovanniSM20** [comment]
oh, sure!

**Comment by eduardsi** [comment]
Closed, moved to https://github.com/watch-devtube/web/issues/47
