### ISSUE TITLE
Make it PWA

### ISSUE THREAD

**Issue by GiovanniSM20** [watch-devtube/web#47]
I think there is a certainty in your description regarding the web app just because one of the web app features is: Installable - Allows users to "save" the most useful applications on their home screens without having to access an app store. So lacking a manifest.json and one other thing is: Independent connectivity - Enhanced with service workers to work offline or on low-quality networks. That can be used a tool called [Workbox](https://developers.google.com/web/tools/workbox/).

**Comment by Developerayo** [comment]
Currently on this feature @eduardsi 

For now we can work with a PWA the later on a Mobile App!
PWA is a perfect start.

**Comment by eduardsi** [comment]
Hey @Developerayo 

Do you have any idea how the app can be turned into PwA with the least amount of effort? What will be the gains for the users?

**Comment by GiovanniSM20** [comment]
I've putted some tool you can try to do that...

**Comment by Developerayo** [comment]
@eduardsi will be pushing this weekend!

Thanks @GiovanniSM20

**Comment by sizovs** [comment]
I am closing this, as the future of dev.tube is Mobile + Elektron app.
