### ISSUE TITLE
New design wireframe concept

### ISSUE THREAD

**Issue by wbhob** [watch-devtube/web#54]
Hi, there,
I really like the concept for DevTube, but the design is a little bit cluttered and unintuitive. I feel like it shows too much irrelevant information to the user, rather than content they could watch. Here's a simple wireframe concept I put together that can help.

This design consolidates and minifies the toolbar and sidebar, making room for more videos, and gets rid of the irrelevant "recorded" and "likes" metadata. It also gets rid of the toggle at the top right for different filter methods, and instead, moves it to the sidebar. I hope this helps.

![desktop](https://user-images.githubusercontent.com/4442130/43349386-698b61ec-91cd-11e8-894d-68652a90d6db.png)

**Comment by eduardsi** [comment]
Thanks for the concept, @wbhob. We took most of your ideas and implemented them in a new version of DevTube. We shipped a new version today. Huuuge thanks!

https://twitter.com/WatchDevTube/status/1029435298957193218

**Comment by wbhob** [comment]
@eduardsi looks awesome, and so much cleaner! I am super happy to help 😄
