### ISSUE TITLE
Add sorting by views.

### ISSUE THREAD

**Issue by rafcioki** [watch-devtube/web#56]

**Comment by eduardsi** [comment]
Hi @rafcioki 

Thanks for raising this. Can you provide more details? What would it help you and users?

**Comment by rafcioki** [comment]
Hi @eduardsi, sorry, I probably should have provided a better description from the beginning. I think it'd make sense to add a possbility to sort the videos by views count (similar as it can be sorted by featured, rating etc) as that's the way people often sort stuff, by popularity - personally I'd find that useful. If you guys are busy with other stuff at the moment I'd be happy to work on this.
