### ISSUE TITLE
Github and Google login doesn't work :(

### ISSUE THREAD

**Issue by vsalles1982** [watch-devtube/web#58]
console log output
[dev.tube-1533768463965.log](https://github.com/watch-devtube/web/files/2272272/dev.tube-1533768463965.log)

**Comment by eduardsi** [comment]
@vsalles1982 what's the OS/browser/version?

**Comment by eduardsi** [comment]
We are seeing growing number of users who use both GitHub and Google for authentication. Closing this until more detail report is provided.
