### ISSUE TITLE
Search only works with exact match

### ISSUE THREAD

**Issue by ankitprahladsoni** [watch-devtube/web#61]
When I search `java design pattern`, I get only 3 results. And when I search 'java design patterns`, I get 10 new results, and the previous 3 results aren't part of this new search result.

**Comment by eduardsi** [comment]
Hey @ankitprahladsoni. Thanks for raising this! Search box supports wildcards, so you can try

`java design pattern*`

Always matching wildcards would be a significant performance overkill and could lead to issues such as finding `javascript`, when `java` is searched.
