### ISSUE TITLE
Tags, speakers and channels should be searchable.

### ISSUE THREAD

**Issue by ankitprahladsoni** [watch-devtube/web#62]

**Comment by eduardsi** [comment]
@ankitprahladsoni Thanks for reporting this. Taking into account the limitation of current search implementation, it won't be added in the foreseeable future. The workaround is using full text. For example:

If you want to find TDD videos by Sandro Mancuso, just type `mancuso tdd`. 

Another example: to find DevTernity conference's architecture videos by Simon Brown, just type `devternity simon architecture`

Probably not the best solution, but at least something that works ATM.
