### ISSUE TITLE
Send search tips (e.g. wildcards) to newly authenticated user's inbox

### ISSUE THREAD

**Issue by sizovs** [watch-devtube/web#63]

**Comment by GiovanniSM20** [comment]
Can you explain this better ?

**Comment by eduardsi** [comment]
@GiovanniSM20 Text search supports wildcars on both sides of a search term (e.g. `jav*`) will match everything that starts with `jav`, `*jav` match everything that ends with `jav`.

**Comment by GiovanniSM20** [comment]
Oh that's great
