### ISSUE TITLE
Video doesn't fit in 1366x650 window tab

### ISSUE THREAD

**Issue by ankitprahladsoni** [watch-devtube/web#65]
either the top or the bottom doesn't fit completely inside the tab.
Using Chrome 68 on 15 inch monitor,
Screen Resolution: 1366 x 720
Bookmark bar is set to visible in chrome

**Comment by eduardsi** [comment]
Hey @ankitprahladsoni 

Thanks for reporting. Can you attach screenshot please? Thanks!

**Comment by ankitprahladsoni** [comment]
![image](https://user-images.githubusercontent.com/8023641/45354744-69361100-b58c-11e8-9b95-75ab133c06b3.png)
As you can see, the top part is little cropped if I try to fit the bottom part of the video in the window.

**Comment by eduardsi** [comment]
@ankitprahladsoni we're now having issues with deployment thanks to an issue on GCF side. Once the deployment is fixed, the solution should be visible: https://travis-ci.org/watch-devtube/web
