### ISSUE TITLE
Add cursor: pointer to the logo of DevTube navigation header

### ISSUE THREAD

**Issue by Stralos** [watch-devtube/web#66]
<img width="2560" alt="screen shot 2018-09-12 at 10 47 52" src="https://user-images.githubusercontent.com/9497563/45409991-59482b00-b679-11e8-8856-2035d0a072df.png">

The logo inside of DevTube is clickable and navigates the user to the main page, but it does not have a pointer cursor. 

A fix is adding cursor pointer to the highlighted dom element.

**Comment by eduardsi** [comment]
Thanks for reporting, @Stralos. It's fixed here: https://github.com/watch-devtube/web/commit/3172be608183c485c17686f5a58bdbf348a379bc

We're having deployment issues, so the change will be visible one we go live.
