### ISSUE TITLE
JS needs to be Minified

### ISSUE THREAD

**Issue by Developerayo** [watch-devtube/web#72]
Minifying JavaScript files can reduce payload sizes and script parse time.

**Comment by GiovanniSM20** [comment]
or even refactor the code...

**Comment by eduardsi** [comment]
Hey @Developerayo 

Can you point to specific JS files that are not minified? 

Thanks!

**Comment by GiovanniSM20** [comment]
@eduardsi Did you have an automation for minified files ?

**Comment by eduardsi** [comment]
@GiovanniSM20 yes, all static resources that are loaded from Dev.Tube (css, js, html) are minimised at the reverse proxy (CloudFlare): 
![image](https://user-images.githubusercontent.com/2264968/48540144-fa45a300-e8c1-11e8-901b-ea96096c82bb.png)

**Comment by GiovanniSM20** [comment]
:heart:
