### ISSUE TITLE
Module not found: Error: Can't resolve '../../firebase.json' in '/workspace/web/express/src/api'

### ISSUE THREAD

**Issue by jankeromnes** [watch-devtube/web#77]
Hello!

I was following the instructions in your README.md in order to build and run dev.tube myself, but then I hit a problem in the server app.

In the `express/` directory, after running `yarn` and pre-populating the `data/` directory with `loki.json`, `lunr.json` and `board.json`, I get the following error:

```bash
$ yarn run dev

# ...

ERROR in ./src/api/user.ts
Module not found: Error: Can't resolve '../../firebase.json' in '/workspace/web/express/src/api'
 @ ./src/api/user.ts 4:21-51
 @ ./src/app.ts
 @ ./index.ts

ERROR in [at-loader] ./src/api/user.ts:3:33 
    TS2307: Cannot find module '../../firebase.json'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

To reproduce this bug yourself, please open my fork in Gitpod, by following this link:
https://gitpod.io/#https://github.com/jankeromnes/web

This will automatically execute [these init tasks](https://github.com/jankeromnes/web/blob/d6c7a18465476e3432c1b4448304fc717576ed07/.gitpod.yml#L7-L15) (copied from your README.md) and in the left Terminal you'll eventually see the problem appear:

<img width="1552" alt="Screenshot 2019-07-25 at 11 45 13" src="https://user-images.githubusercontent.com/599268/61864424-b172cf00-aed1-11e9-8da0-b28f764395bd.png">

**Comment by sizovs** [comment]
Hi @jankeromnes 

Thanks for raising this.

For the time being, it's not possible to run DevTube locally without giving permissions to the centralized Google DataStore. I have updated README.md accordingly, warning contributors about the limitation.

If you could help us mock-out datastore, that would be an extremely valuable contribution.

**Comment by jankeromnes** [comment]
> If you could help us mock-out datastore, that would be an extremely valuable contribution.

I'd love to help with that! Is it basically planting a fake `firebase.json`, and filling it with mock data until the app stops throwing errors?

Any suggestions on how to begin? 🙂

**Comment by sizovs** [comment]
If we can feed Firebase with a fake `firebase.json`, that would be a good starting point. The next step is stubbing datastore with https://www.npmjs.com/package/google-datastore-emulator and feeding it with some data when the application runs in dev mode.

**Comment by sizovs** [comment]
Hi @jankeromnes 

Finally, we've made it possible to run DevTube on a local machine. Please see README.md.
