### ISSUE TITLE
General Improvments

### ISSUE THREAD

**Issue by MeikelLP** [watch-devtube/web#78]
I just texted with @sizovs via email and asked about his opinions about the following topics:

* [ ] Purpose of the index.pug file and its "pug variables".
  > The index file needs to be static to be recognized by search engines. Meta variables must not be set by Javascript.
  > Variable such as `NightMode` can be refactored.

  * [x] Let's make a list what variables can be refactored and which must not be refactored.

  I would like to have the meta info in a config file and have that compiled into the index file when building (still static).

* [ ] Decouple client-side and server-side. 
  > @sizovs Suggests using https://github.com/typicode/json-server
  IMHO this might be even overkill as with the Vue CLI (and the integrated dev server) we can proxy requests to the production server or even to local json files (would still require copies of the json files).

  Helpful links:
  * https://cli.vuejs.org/config/#devserver-proxy
  * https://webpack.js.org/configuration/dev-server/#devserver-proxy

**NEW**

* [ ] Integrate the Vue CLI. Every new Vue app is created using the CLI and developed using its dev tools. Migrating isn't hard (already works locally) but the `index.pug` file and the general client-server depedency breaks every advantage of using the CLI.

**Purpose**

* As a normal frontend and Vue developer I wanted to checkout this project but stumbled across too many hardships that my motivation went down. My motivation went up as I thought about improving this project as it is open soruce (thank you very much). I texted @sizovs and he kindly responded with an open mind. So here we are. 

Please leave feedback and discuss so we can start improving dev.tube :)

**Comment by sizovs** [comment]
removing server-side rendered variables from `index.pug`:
- [ ] window.preloadedEntity = move to client-side. Used in direct video links `//dev.tube/video/<id>`
- [ ] window.serverSideError = unused
- [ ] window.newVideos = unused
- [ ] window.board = move to client-side. Used in leaderboard.
- [ ] window.speaker = move to client-side. Used in speaker profiles `//dev.tube/@sizovs`
- [ ] window.brownbag = unused (brownbag functionality has been commented out)
- [ ] window.featured = move to client-side. Data for channels, tags and speakers list.

**Comment by MeikelLP** [comment]
How about different config files for different environments? In development you don't need meta tags so they could be omitted in the config file but must exist in the `production.env` file. This could be checked via a test.

AFAIK it's not very common to reference hard dependencies outside of the Vue SPA. The common way is to have different environments defined with different environment variables ([vue cli docs](https://cli.vuejs.org/guide/mode-and-env.html)). I think that this is the right way because the app itself becomes independent and can run without errors in itself.

**Comment by sizovs** [comment]
Meta tags are not app-wide but are video-specific. Whenever someone browses to a video, the server generates `index.html` with meta tags specific to that video.

**Comment by MeikelLP** [comment]
Ah okay so these pages needs to be generated statically? Maybe we should look into [Nuxt.js](https://nuxtjs.org/) ?

**Comment by sizovs** [comment]
That would be a pretty big change with its dragons.

Maybe a dev-server can generate a fixed or an empty list of tags?

**Comment by MeikelLP** [comment]
Yes I see that exactly like you but I think that will be the best way we have to go in the future.

What exactly do you mean? I don't think the dev server (at least the webpack dev server) is able to do this. But I don't know too much about it.

**Comment by sizovs** [comment]
We can pass data to html-webpack-plugin: https://github.com/jantimon/html-webpack-plugin/issues/747

**Comment by MeikelLP** [comment]
Ah okay never thought/heard about that: https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates

I'll try looking into it.

**Comment by MeikelLP** [comment]
Is dev tube an equal use case of this? https://github.com/vuejs/vue-hackernews-2.0/

If yes what do you think about it? https://ssr.vuejs.org/

**Comment by sizovs** [comment]
No doubt SSR a good thing and has its use cases. Current dev.tube version could have been implemented using architecture similar to`vue-hackernews`.

**Comment by MeikelLP** [comment]
So you think it's an reasonable approach to follow right now?

**Comment by sizovs** [comment]
Yes, it could be. But we'd better evolve the application in small steps, without introducing big and risky changes to the system. I'd start with defining the problem that we're trying to achieve:

1. Define a problem
2. Define a list of possible solutions
3. Choose the best solution (small, cheap, risk-free)
4. Execute

**Comment by MeikelLP** [comment]
Okay do you have any plans for the first steps towards SSR? Because you know your app better than me. You might know what parts can be altered easily or what parts need a complete rewrite.

**Comment by sizovs** [comment]
We don't have new use cases for SSR yet.

**Comment by MeikelLP** [comment]
Are there parts that can not be rendered server side?

Right now are there certain that could be handled via SSR? If yes it could be possible to incrementally move the whole website to SSR (?)

**Comment by sizovs** [comment]
It's hard to say without actually moving to server-side: unmoveable parts, if any, will be discovered only during migration.

For now, the website has been developed without considering SSR. I assume that migration will take a significant amount of time, even if done incrementally. That's why it's important to answer the question `why` before committing to it.

**Comment by MeikelLP** [comment]
IMO it decouples the server-client or to be more precise it merges them so you only have one to care about. 

The ultimate goal should be that the project is simply just a `checkout`, `install packages` and `run`. It may not contain all data equal to the production server but that should be fine. I personally hate it when projects require you to do many steps before I'm able to run the app locally (excluding dev tools/ system dependencies).

IMHO I think that the complexity to setup this project is currently not justifiable. I want to improve that. I currently see SSR as `the solution` but I don't have experience with it. I can only argue by the theory of it. 

Do you have other folks that work with you on the dev.tube project? What do they think?

**Comment by sizovs** [comment]
I agree that the complexity can be reduced and the ideal way of running the would be checkout&run. But turning on SSR won't magically make the setup easier. As with every migration project, it takes time and effort to accomplish. Our goal is to make setup easier, not to immerse into SSR migration, right?

I recommend understanding what limits the app from running locally and addressing each problem separately. Like outsmarting `index.pug` variables. Then moving to the next problem, understanding and solving it.

**Comment by MeikelLP** [comment]
My thoughts were just that we could hit 2 birds with one stone and improve the design of the app overall. IMHO it could be a waste of time if we first fix some minor issues that might be resolved when doing it directly the "correct" way.

Dev.Tube doesn't look too big too have this change. And it could be done in parallel while the app in the current stage is doing like it does right now and then switch to the version 2.0 once its time has come. Just like Twitter did it with their new design.

**Comment by MeikelLP** [comment]
I just opened a PR where I improve the styling of the page (and remove `nightMode` as it is). I cannot fully test all possible views as the app is not correctly working locally (firebase and stuff). Can you please provide feedback on #79

**Comment by sizovs** [comment]
Let's start from scratch and make a more specific roadmap of improvement. No revolutions, small change at a time.
