### ISSUE TITLE
Add a description of what the site does

### ISSUE THREAD

**Issue by NightMachinary** [watch-devtube/web#88]
Does it scrape certain channels? Certain keywords? How does it work?

**Comment by aadamovich** [comment]
Hi! 

Contribution guidelines are described here: https://github.com/watch-devtube/contrib (there is also a link on the main website).

**Comment by aadamovich** [comment]
Basically, there is a list of channels contributed by the community that is scraped nightly and the index of videos is updated.

**Comment by aadamovich** [comment]
https://github.com/watch-devtube/contrib/blob/master/channels.yml
